### ISSUE TITLE
v1.5 fix not working with Radeon graphics

### ISSUE THREAD

**Issue by Crybt0** [zocker-160/Soldiers-HoWW2-widescreen-fix#3]
v1.3 was working only with 800x600 resolution and this v1.5 is working only with 1024x768 resolution, no higher resolution options available. Also Video settings are only low or medium
![1024x768 resolution](https://user-images.githubusercontent.com/103536582/163052653-64a9215b-76cd-48c6-8bc1-605bdb35574b.png)
.

**Comment by zocker-160** [comment]
what is your desktop resolution?

Please try resetting your profile (or create a new one for testing) and set the resolution in the settings to `Use desktop settings` which should use the same resolution as your desktop and report back, if that changes anything for you.

**Comment by Crybt0** [comment]
I have 2 monitors, both are 2560x1440 first one is 165hz and second is 90hz.

i tried resetting profile and also tried creating new. Quality is not good with "using desktop settings". Also tried with v1.3 and there was option to use 2560x1440 resolution, but all text are unreadable.

It shows same resolution when using "use desktop settings", when applied that, it will change my desktop resolution to 1024x768. if i change desktop resolution back to 2560x1440, game goes small "windowed" to top left corner(when game is on).

Is there way to slow camera moving speed more than in game?

Rest pc specs:
Amd Ryzen 3700x
Gigabyte Radeon 5700xt
32GB DDR4 3200Mhz
M.2 SSD 1TB
Win 10 Home 21H2 19044.1586

**Comment by zocker-160** [comment]
> I have 2 monitors,

Could you try with just one monitor pls and see if that fixes the problem? The game does not support multi monitor setups and usually causes a crash without my patch.

**Comment by Crybt0** [comment]
Tried with only one at time, didnt work. My friend have two monitors and this fix works on his setup. he have i7-3770k with GTX 10xx gpu.

**Comment by zocker-160** [comment]
yeah it looks like the AMD GPU has some problems with DX8, which is not surprising considering the problems other ppl have with other old games that also use DX8.

I sadly do not have an AMD GPU available for testing :(.

**Comment by Crybt0** [comment]
![v1 3 with 2560x1440x165hz](https://user-images.githubusercontent.com/103536582/163271981-414ed083-a27f-4ee7-a0ec-1a9c7f11572d.png)
v1.3 with 2560x1440x165hz

![v1 3 with 640x480 setting on](https://user-images.githubusercontent.com/103536582/163272062-e3a03263-84d9-4837-97a3-6e7bee44ee28.png)
i can only start game with 640x480 setting on and it gives me these settings.

pics taken with v1.3 fix

I have other Dx8 games working good.

**Comment by zocker-160** [comment]
oh wow the font is utterly broken, I have never seen that in this game, I sadly do not know a fix for that.

**Comment by Crybt0** [comment]
Got resolution fix working with v1.6 and using 640x480 checked. 

but its really annoying that desktop resolution is changed after closing game.

**Comment by zocker-160** [comment]
ok glad to hear, you got it working somehow.

I sadly do not have any AMD GPU for testing, so I sadly cannot help you with this issue. :V ._.
