### ISSUE TITLE
Not working under Win XP

### ISSUE THREAD

**Issue by vorob1** [zocker-160/Soldiers-HoWW2-widescreen-fix#4]
Yep... That's me... Playing old game on old pc for retro games. When i unpack these two files exe will give me an error:

InitializeCriticalSectionEx in KERNEL32

Maybe there is another way to increase fov?

**Comment by zocker-160** [comment]
does this issue happen on both v1.3 and v1.5?

I sadly currently have no way to test on XP ._.

**Comment by vorob1** [comment]
Sadly it's not working :
![1 3](https://user-images.githubusercontent.com/36692361/165817667-3d331fbf-4943-454b-b3f9-29e422451720.JPG)
![1 5](https://user-images.githubusercontent.com/36692361/165817671-b4fbac61-e7f8-4122-9de6-aea5021f03af.JPG)

**Comment by zocker-160** [comment]
@vorob1 could you please retest with this build:
[WidescreenFix_v1.5_XP.zip](https://github.com/zocker-160/Soldiers-HoWW2-widescreen-fix/files/8585556/WidescreenFix_v1.5_XP.zip)

**Comment by vorob1** [comment]
Thanks for your efford, but it's new error now :)

If it takes time, don't bother. I think i'm the only person you'll see who wanna play old game on retro os but with newgen mod :)

![4234234](https://user-images.githubusercontent.com/36692361/165832990-8e82407b-945b-4b34-9502-36b5321fe0ea.JPG)

**Comment by vorob1** [comment]
Oh it also gives next error - unable to load widescreenfix.asi error: 127

And then game starts.

**Comment by zocker-160** [comment]
ah so the kernel.32.dll is gone, that is good, at least some progress.

That runtime error is weird though. Are you running XP SP3?

**Comment by vorob1** [comment]
Well, your question bothered me so i've checked on another win xp laptop with clean windows. No errors. But also no zoom benefits i'm looking for. Just for my personal interest i've rechecked 1.3 and 1.5 from release folder and they both give kernel error on clean windows.

**Comment by zocker-160** [comment]
> Well, your question bothered me so i've checked on another win xp laptop with clean windows. No errors. But also no zoom benefits i'm looking for

what resolution is it running at?

The FOV fix will only kick in, if you have a higher aspect ratio than 1,77

**Comment by zocker-160** [comment]
and could you enable debug mode and check what the output ist?

**Comment by zocker-160** [comment]
I pushed a small update for XP and added the option to enforce the camera patch regardless of aspect ratio
[WidescreenFix_v1.6.zip](https://github.com/zocker-160/Soldiers-HoWW2-widescreen-fix/files/8586682/WidescreenFix_v1.6.zip)

make sure you set `enforceCamPatch` to 1 in the ini

**Comment by vorob1** [comment]
Sir, it works! But for some reason my pc reboots when I’m trying to interact with my units. This happens only on extreme level of zoom out. Will play more and get back. 

![C82FB33B-3A8A-4E3D-96D0-75588A127953](https://user-images.githubusercontent.com/36692361/165902310-31c34a5c-d822-4e0b-98cd-17e3bbd6fe38.jpeg)

**Comment by vorob1** [comment]
Fixed my first laptop. I had to reinstall The Visual C++ Redistributable Packages 2015. For some reason previous installation was not correct, it was some bundle Visual Studio 2015, 2017, 2019 and 2022, but despite it was official package from Microsoft and was installed without errors your mod wasn’t working. So I uninstalled this bundle and installed just one 2015 visual studio. Now it works. 

And looks like my first marching isn’t rebooting, but I’ll do additional testing.

**Comment by zocker-160** [comment]
nice glad to hear!

> This happens only on extreme level of zoom out

Yeah that is possible, the game really does not like very high FOV or high zoom out levels and tends to crash. The default values in the ini are tested on 21:9 (which is actually the main aspect ratio of this patch) so YMMV.

**Comment by vorob1** [comment]
Already completed two missions with your mod using high zoom out feature and everything goes smoothly, thank you very much! 

And since we are here I’ve got some off topic question. Usually I am using WSAD to scroll my map, but for some reason, in this game, when you scroll map with keyboard and move mouse cursor the game lags horribly. This happens on my retro PC and this also happens on my modern PC so it’s a game issue. Maybe you have a clue why it happens?

**Comment by zocker-160** [comment]
yeah the lag is a known problem and it is cause by how the game implement the game cursor replacing it with a custom renderer.

A solution would be to enforce the Windows cursor, but I didn't look into that yet, so I don't know how much work that is.

**Comment by Neustradamus** [comment]
Someone can help to have an "InitializeCriticalSectionEx" fix in VxKex/VxKex-NEXT?
- https://github.com/YuZhouRen86/VxKex-NEXT/issues/98
- https://github.com/i486/VxKex/issues/156

Thanks in advance.

**Comment by zocker-160** [comment]
The WinXP build available above should fix this problem, I am not sure what else needs to be done here.

There might be other issues though, but I don't have an WinXP machine to test it myself.

EDIT: seems like you are posting this exact message to all GitHub issues that mention `InitializeCriticalSectionEx`. Sorry I cannot help in that regard.
