### ISSUE TITLE
Support for Super-Ultrawide 5120x1440

### ISSUE THREAD

**Issue by zocker-160** [zocker-160/Soldiers-HoWW2-widescreen-fix#5]
As requested by ppl on ModDB. If you have such screen please let me know, because I cannot test it sadly ._,

**Comment by juaxoo** [comment]
Hi, thanks for raising this. I can test. Just let me know what is needed.

**Comment by zocker-160** [comment]
@juaxoo small update from my side. I have a version for testing for you:
[WidescreenFix_v1.6.zip](https://github.com/zocker-160/Soldiers-HoWW2-widescreen-fix/files/8693697/WidescreenFix_v1.6.zip)

please make sure you:

- delete all of the old files from this patch (`d3d8.dll` and `d3d8.ini`)
- copy the new files from the zip
- set `superUltrawideSupport` in the new ini to `1`

please let me know if it works and especially how the camera height and zooming works as one would expect

**Comment by juaxoo** [comment]
@zocker-160 I deleted old files and put in new ones directly next to .exe file.
 Got following error:

E:\Steam\steamapps\common\Soldiers Heroes of World War 2\Soldiers.exe 
Soldiers: Heroes Of World War II, ver 1.28.3E [14.05.2022, 21:22]
Total video memory reported: 4265607168
Local video memory detected: 1726152704

***************** Exception *****************
Texture or surface size is too big (esurface.cpp, 129)
------------------------------------------------------------------


Tried to also reinstall the game (did the compatibility and disable full screen optimization settings as well) but still got the same error
Also set "superUltrawideSupport = 1"
Fix still works up to 3440x1440

**Comment by zocker-160** [comment]
ok try again with this version:
[WidescreenFix_v1.6.zip](https://github.com/zocker-160/Soldiers-HoWW2-widescreen-fix/files/8693933/WidescreenFix_v1.6.zip)
 
same instructions as above

**Comment by zocker-160** [comment]
@juaxoo

**Comment by juaxoo** [comment]
Wow, you made it work. Here are screen with max zoom out and zoom in. I kinda wish if I could zoom out just a few percent more but Its usable this way. When I was using the 3440x1440 I could zoom out more but there was this FOG which increased with every scroll. Right now its not happening which is good.

![scr0-min](https://user-images.githubusercontent.com/105510775/168491734-5845bce3-4fe9-4d92-a22a-b837c0d18e87.png)
![scr1-min](https://user-images.githubusercontent.com/105510775/168491737-32c19d97-7497-486d-9e8d-8ebcf0301be6.png)

**Comment by zocker-160** [comment]
@juaxoo nice! You can change the zoom limits in the ini file, so if you want to zoom out more, feel free to change those values.

Just keep in mind that too crazy values will crash the game.

**Comment by zocker-160** [comment]
I pushed this update as v1.6, closing this issue.

If there is anything additional that needs to be fixed, feel free to comment and / or reopen.

**Comment by juaxoo** [comment]
All is working flawlessly, adjusted the zoom limits as you advised and Im very happy now. Thank you so much !
